name: resume_web_app
description: Louis Deveseleer resume

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  transparent_image: ^1.0.0
  dough: ^0.3.6
  google_fonts: ^1.1.1
  device_preview: ^0.4.8
  carousel_slider: ^2.3.1
  draggable_scrollbar: ^0.0.4
  flutter_linkify: ^4.0.2
  universal_html: ^1.2.1
  ext_video_player: ^0.0.4
  easy_web_view: ^1.3.1
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/
    - web/icons/
    - fonts/
