name: resume_web_app
description: Louis Deveseleer resume

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  chewie: ^1.0.0
  cupertino_icons: ^1.0.2
  dough: ^1.0.1
  draggable_scrollbar: ^0.1.0
  firebase_core: ^1.0.4
  firebase_storage: ^10.2.17
  flutter_linkify: ^5.0.2
  google_fonts: ^3.0.1
  transparent_image: ^2.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.3
  video_player: ^2.1.1
  youtube_plyr_iframe: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/
    - web/icons/
    - fonts/
